include:  package:pedantic_mono/analysis_options.yaml


analyzer:
  errors:
    prefer_final_in_for_each: ignore
    unnecessary_nullable_for_final_variable_declarations: ignore
  exclude:
    - '**/*.g.dart'
    - '**/*.config.dart'
    - '**/*.freezed.dart'
    - '**/*.mocks.dart'
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "**/messages_*.dart"
    - '**/messages_*.dart'
    - /**/messages_*.dart

linter:
  rules:
    # Error Rules
    - always_use_package_imports
    - prefer_expression_function_bodies
    - avoid_print
    - avoid_slow_async_io
    - cancel_subscriptions
    - close_sinks
    - control_flow_in_finally
    - hash_and_equals
    - collection_methods_unrelated_type
    - literal_only_boolean_expressions
    - unnecessary_statements
    - use_build_context_synchronously
    # Style Rules
    - avoid_bool_literals_in_conditional_expressions
    - avoid_field_initializers_in_const_classes
    - avoid_function_literals_in_foreach_calls
    - avoid_positional_boolean_parameters
    - avoid_redundant_argument_values
    - avoid_renaming_method_parameters
    - avoid_returning_null_for_void
    - avoid_returning_this
    - avoid_setters_without_getters
    - avoid_types_on_closure_parameters
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - cascade_invocations
    - constant_identifier_names
    - exhaustive_cases
    - file_names
    - implementation_imports
    - join_return_with_assignment
    - no_default_cases
    - non_constant_identifier_names
    - null_check_on_nullable_type_parameter
    - overridden_fields
    - prefer_asserts_in_initializer_lists
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_constructors_over_static_methods
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_function_declarations_over_variables
    - prefer_if_elements_to_conditional_expressions
    - prefer_initializing_formals
    - prefer_interpolation_to_compose_strings
    - prefer_is_not_operator
    - prefer_null_aware_operators
    - prefer_typing_uninitialized_variables
    - sized_box_for_whitespace
    - sort_unnamed_constructors_first
    - tighten_type_of_initializing_formals
    - unnecessary_await_in_return
    - unnecessary_lambdas
    - unnecessary_null_aware_assignments
    - unnecessary_null_checks
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - use_is_even_rather_than_modulo
    - use_late_for_private_fields_and_variables
    - use_named_constants
    - use_raw_strings
    - use_string_buffers
    - use_to_and_as_if_applicable
    - void_checks
