synthetic-package: false
arb-dir: lib/config/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
untranslated-messages-file: missingTranslations.txt
nullable-getter: false