name: tile_flow
description: "Tile flow project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.17
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  go_router: ^14.8.1
  injectable: ^2.5.0
  intl: any
  json_annotation: ^4.9.0
  logger: ^2.5.0

dev_dependencies:
  analyzer: ^7.3.0
  build_runner: ^2.4.15
  dependency_validator: ^5.0.2
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.4
  pedantic_mono: ^1.30.3

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/logo/
